In [2]:
!pip install pandas numpy mysql-connector-python streamlit

Requirement already satisfied: pandas in c:\users\bhara\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\bhara\anaconda3\lib\site-packages (2.3.5)
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: streamlit in c:\users\bhara\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bhara\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\bhara\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\bhara\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: packaging<26,>=20 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\bhara\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\bhara\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\bhara\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\bhara\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\bhara\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\bhara\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\bhara\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\bhara\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bhara\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\bhara\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bhara\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: attrs>=22.2.0 in c:\users\bhara\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\bhara\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\bhara\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\bhara\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\bhara\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\bhara\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
    --------------------------------------- 0.3/17.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.8/17.7 MB 5.5 MB/s eta 0:00:03
   ------ --------------------------------- 2.9/17.7 MB 5.9 MB/s eta 0:00:03
   --------- ------------------------------ 4.2/17.7 MB 5.7 MB/s eta 0:00:03
   ------------ --------------------------- 5.5/17.7 MB 5.9 MB/s eta 0:00:03
   --------------- ------------------------ 6.8/17.7 MB 6.0 MB/s eta 0:00:02
   ------------------ --------------------- 8.1/17.7 MB 6.0 MB/s eta 0:00:02
   -------------------- ------------------- 9.2/17.7 MB 6.0 MB/s eta 0:00:02
   --------------------- ------------------ 9.4/17.7 MB 5.7 MB/s eta 0:00:02
   --------------------- ------------------ 9.4/17.7 MB 5.7 MB/s eta 0:00:02
   --------------------------- ------------ 12.1/17.7 MB 5.4 MB/s eta 0:00:02
   ----------------------------- ---------- 13.1/17.7 MB 5.4 MB/s eta 0:00:01
   -------------------------------- ------- 14.4/17.7 MB 5.5 MB/s eta 0:00:01
   ----------------------------------- ---- 15.7/17.7 MB 5.5 MB/s eta 0:00:01
   -------------------------------------- - 17.0/17.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 5.3 MB/s  0:00:03
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [3]:
import pandas as pd
import numpy as np
import mysql.connector
from mysql.connector import Error

In [8]:
df = pd.read_csv(r'C:\Users\bhara\OneDrive\Desktop\Guvi\Uber Eats\Uber_Eats_data.csv')
print("Original rows:", df.shape[0])

Original rows: 23193

In [9]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [10]:
print("Before Cleaning:", df.shape)
df = df.drop_duplicates()
df = df.dropna(subset=['name', 'location', 'rate'])

Before Cleaning: (23193, 13)

In [12]:
#Clean Rating
df['rate'] = df['rate'].astype(str).str.replace('/5','',regex = False).str.strip()
df['rate'] = pd.to_numeric(df['rate'], errors = 'coerce')
df['rate'] = df['rate'].fillna(df['rate'].median())

In [13]:
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(str).str.replace(',', '', regex=False)
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'], errors='coerce')
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].fillna(df['approx_cost(for two people)'].median())

In [14]:
# Feature Engineering
df['price_segment'] = pd.cut(df['approx_cost(for two people)'],
                             bins=[0, 400, 800, 1500, float('inf')],
                             labels=['Low', 'Mid', 'Premium', 'Ultra-Premium'])

In [15]:
df['online_order'] = df['online_order'].map({'Yes': 1, 'No': 0, 'Yes ':1}).fillna(0).astype(int)
df['book_table'] = df['book_table'].map({'Yes': 1, 'No': 0, 'Yes ':1}).fillna(0).astype(int)

In [24]:
print("After cleaning:", df.shape)
import os
os.makedirs('data/cleaned', exist_ok=True)
df.to_csv('data/cleaned/restaurants_cleaned.csv',index=False)
df.head()

After cleaning: (23158, 14)

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city),price_segment
0,Jalsa,1,1,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Mid
1,Spice Elephant,1,0,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,Mid
2,San Churro Cafe,1,0,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,Mid
3,Addhuri Udupi Bhojana,0,0,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,Low
4,Grand Village,0,0,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,Mid